import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
     
      <header className='flex items-center justify-center my-[2%]  '>
        <div className="bg-zinc-800 w-[97%] h-[100px] flex justify-between" >
          
          <div className="flex w-1/2">
          <img src="IMG/x-icon.png" alt="logo" className='mxr-[10%] w-16 h-16 m-4 bg-zinc-600 rounded-full'></img>
            <div className="bg-zinc-600 rounded-[20px] inline-flex w-80 h-10 my-7">
            <img src="IMG/lupa.png" alt="lupa" className="w-12 rounded-[20px]"></img>
              <form >
                <input type="text" className='bg-zinc-600 my-2 text-white w-[90%]'></input>
              </form>
            </div>
          </div>
          <div className='flex'>
            <img src="IMG/Cart.png" alt="cart" className='w-16 h-16 m-4 bg-zinc-600 rounded-full '></img>
            <img src="IMG/UserPhoto.png" alt="UserImg" className='w-16 h-16 m-4 rounded-full'></img>
          </div>
        </div>
      </header>
      {children}
      </body>
    </html>
  )
}
